### PR TITLE
Add publication to Maven Central

### PR DESCRIPTION
**Pull request by aalmiray**
Requires setting up `MAVEN_USERNAME` and `MAVEN_PASSWORD` as environment variables.
Recommend bumping version to `3.0.1`.
Configure bintray repository to automatically sign artifacts before attempting the next `bintrayUpload` task. Edit the package properties on Bintray, search for GPG.

### CODE REVIEW

**Comment by dukke** [comment]
Hi aalmiray!

Somehow I missed this.

Truly sorry for that, I'll look into this tomorrow.

Sorry and thanks,

**Comment by dukke** [comment]
Hi again @aalmiray 

I've already enabled GPG signing on bintray.

I'm new to Maven Central. Newbie question: how do I get a username, password with access to org.jftras ?

Thanks :)

**Comment by tbee** [comment]
From what I remember is that you get a personal set of private and public keys, and then those get the right to publish under a certain groupId. But that was setup years ago, and it has been running ever since automatically. So I need to dig into that again.

**Comment by aalmiray** [comment]
@dukke someone from the JFXtras organization (perhaps @tbee) already has access to a username/password. Either they grant you access by sharing the username/password OR you grant them access to your bintray repository (as admins I think) so that they can push the "Sync to Maven Central" button.

**Comment by tbee** [comment]
If I give you my set of keys then you will also be able to publish under e.g. MigLayout, so that is not the way. It must be a personal key AFAIK.

**Comment by dukke** [comment]
@aalmiray I think @tbee is right. 

From what I had time to read, contributors of jfxtras will also have a personal key to publish to maven central jfxtras. I think there is some kind of automatic association between email and belonging to an organization like jfxtras under maven central.

**Comment by dukke** [comment]
Hi @aalmiray truly sorry for taking so much time to get into this. I talked with the guys that administer Maven Central and I believe I now have the necessary permissions to publish JMetro to jfxtras.
If we get the PR merged, I believe l'll now have all that's required to publish to Maven Central.

I might publish through a Gradle command (I imagine your PR adds such a command) or through the bintray API which has a button to sync to Maven Central.

I'll also probably re-use your script in FXRibbon and other open source projects. If you'd prefer you can also do a PR there.

Thanks @aalmiray !! 👍 




Could you update the PR. I think just some minor changes and we're done.

**Comment by tbee** [comment]
I'm curious how getting that permission works. I assume one of the current owners of the right to publish under jfxtras should give an okay. Like permission management on github. It would be weird if anyone could simply publish under jfxtras. Or is it indeed the idea to share the PGP key that is allowed to sign for the project?

**Comment by tbee** [comment]
Some process like this https://issues.sonatype.org/browse/MVNCENTRAL-3031

**Comment by dukke** [comment]
As far as I understood, they checked the project and saw I was a regular commiter.

**Comment by dukke** [comment]
.. I'm sure they checked the project and so my commits.

**Comment by tbee** [comment]
It's quite ok of course, Pedro. Just curious how they go about it.

**Comment by dukke** [comment]
Sure, no worried Tom 😄

**Comment by dukke** [comment]
Proposed changes in this PR have been manually added to the repo. Thanks for submitting it.

**Pull request closed without merging**
