### PR TITLE
Fix for issue #210

### PR DESCRIPTION
**Pull request by ThomasDaheim**
See https://github.com/JFXtras/jfxtras-styles/issues/210

### CODE REVIEW

**Comment by TheRedSpy15** [comment]
Any word on this getting merged?

**Comment by dukke** [comment]
Hi @ThomasDaheim 

Truly sorry for the late reply, I've been very busy with my work!

Can you make that one change I suggested in the review to the PR?

Thanks and sorry again.

**Comment by ThomasDaheim** [comment]
Hi @dukke 

No worries, we all have a real job to take care of as well ;-)

Somehow I can't find your comment? Probably me trying to fix things on a Sunday... What change did you suggest?

**Comment by dukke** [comment]
Hey @ThomasDaheim , good to hear from you again.

Minor change, I just suggested that you simply remove the commented out line of code that was previously causing issues (instead of commented it out just remove it entirely):
```
 /*-fx-skin: "impl.jfxtras.labs.internal.scene.control.skin.ListSpinnerCaspianSkin";*/
 ```

Thanks!

**Comment by ThomasDaheim** [comment]
Done

**Comment by dukke** [comment]
Thanks @ThomasDaheim !

**Pull request merged**
