### PR TITLE
Updates to work with Java 9 and above

### PR DESCRIPTION
**Pull request by ronymesquita**
The key goal is maintain the original styles and only adapt to work with Java module system.

The changes on the packages names was made to use the convention "groupId:artifactId" and add the implementation packages.

Various samples were added to show the code running.

### CODE REVIEW

**Comment by dukke** [comment]
Hi @ronymesquita . I'm truly sorry but due to a configuration issue I didn't get notified of this PR. 

Would you consider updating the PR?

There's also a few other observations I'd like to make, if you do.

Thank you very much for creating this PR and for contributing back.

**Comment by ThomasDaheim** [comment]
I would really like to see JMetro working with Java9+

**Comment by dukke** [comment]
@ThomasDaheim Would you consider submitting a PR?

**Comment by dukke** [comment]
This has been fixed meanwhile. Thanks!
New versions for 9 and above are already available.

**Pull request closed without merging**
