### PR TITLE
Fix #199

### LINKED ISSUE #199: Collapsing a TreeItem in a TreeView with a selected child causes a visual bug while pressing
Issue: Collapsing a TreeItem in a TreeView with a selected child causes a visual bug at the bottom of the TreeView while pressing the mouse button

Steps to reproduce:
1. Start the same app as in issue #198

grafik
2. Expand "root"

grafik
3. Select "child"

grafik
4. Collapse (and hold) "root". There will be a visual bug at the bottom of the srceen

grafik

EDIT:
The color you see at the bottom is `cell_pressed_color` from `light_theme.css`/`dark_theme.css`. I suspect that this issue is caused by not properly propagating the mouse input to the correct row cell.

### PR DESCRIPTION
**Pull request by Exopandora**
This PR fixes #199. But i don't know if this can cause any side effects

### CODE REVIEW

**Comment by dukke** [comment]
Hi @Exopandora

Sorry for the late reply, I've been very busy with my work.

I can't seem to reproduce this issue in javafx 17. Would it be possible for you to pull the latest version and check?

Sorry again. Cheers.

**Comment by Exopandora** [comment]
Sure, i can do that tomorrow

**Comment by dukke** [comment]
That's awesome! Thanks

**Comment by Exopandora** [comment]
It looks like jfx 17 can't be downloaded anymore

**Comment by dukke** [comment]
I've downloaded it. It's a long term support release so it's still supported.

How are you doing it?

In the build.gradle of the samples subproject, I've put this:
`javafx {
    version = "17.0.0.1"
    modules = [ 'javafx.controls', 'javafx.fxml', 'javafx.swing', 'javafx.web', 'javafx.graphics' ]
}`

**Comment by Exopandora** [comment]
I tested again with jfx 17.0.0.1 and the latest version of jfxtras and the issue is still present. It can be reproduced using [this](https://gist.github.com/Exopandora/eebc52d31aeb94421d8bcae5586fa472) application.

**Comment by dukke** [comment]
Yeah, that's the app I used to test.
Crazy.. let me check what could be going wrong..

**Comment by dukke** [comment]
It doesn't even happen in JavaFX 11 to me.

**Comment by Exopandora** [comment]
All i can add to that is that i'm using windows 10 if that helps. Have you tried a clean clone of the repo yet? I also added a [stylesheet](https://gist.github.com/Exopandora/eebc52d31aeb94421d8bcae5586fa472#file-style-css) to the example app in order to better visualize the bug. It can be added to the example app the following way:
```diff
jMetro.setScene(scene);
+ scene.getStylesheets().add(this.getClass().getResource("style.css").toExternalForm());
stage.setScene(scene);
```

**Comment by Exopandora** [comment]
Additional note: I'm using 125% resolution scaling

**Comment by dukke** [comment]
@Exopandora I think that's what I do.

I've recorded a video to show what I'm doing:

https://user-images.githubusercontent.com/2707487/186225141-8ffb8a52-a2c0-4d39-86bd-7bd60557d112.mp4

**Comment by Exopandora** [comment]
I tried to replicate your setup and the bug did not occur when using intellij/gradle. When application is built and launched manually (with the same jre) but with a bat, the bug is visible. The bug also appears when the application is launched in eclipse.
In the following picture you can see a difference in the arrow size (left is intellij/gradle and on the right is eclipse). The issue appears only on the right.

apps

This is so confusing. I will investigate this further.

**Comment by Exopandora** [comment]
Here a video of the bug in action:
[jmetro#199.webm](https://user-images.githubusercontent.com/18708736/186245812-7c99b433-7cba-423c-a71c-eae0575a603e.webm)

**Comment by dukke** [comment]
It seems that your fix is already in the main repository. Probably the css changed meanwhile, between you cloning the repo and submitting the PR.

Would it be possible for you to clone the main repo again and verify that?

Thanks!

**Comment by Exopandora** [comment]
I can confirm that the proposed fix was already part of commit cde2fb1a8b05f7bc805556993d65f53c86c27ddc.

**Comment by Exopandora** [comment]
I should also make clear that the bug is fixed. Thanks for the troubleshooting.

**Comment by dukke** [comment]
Thank you very much @Exopandora for confirming that this has been fixed!

**Pull request closed without merging**
