### PR TITLE
Button and ToggleButton fixes and improvements.

### PR DESCRIPTION
**Pull request by MairwunNx**
**PLEASE APPLY IT PR AFTER CUSTOM COLORS PR! IT PR HAS CUSTOM COLOR DEPENDESITY!**
**lol, if i not stupid, i think you can just apply it PR, without custom colors PR, it PR contains changes custom color PR**

This pull request fixes the following bugs with buttons and toggle buttons. These exceptions are ABSOLUTELY BROKEN PROGRAM! And it is not possible to use the program due to these exceptions because they can appear through time because of the large stacktrace. This is not related to the independent libraries or to the TornadoFx or the Kotlin language, these problems are on Java, just apparently, you are lucky that you did not meet them. I am using Java 8.

I also want to note that not only did I notice this critical problem, the person who did the update to Java 9 also commented in the code.

Exception on left click:

https://gist.github.com/MairwunNx/1d817c9d4ad3c21ee5b2c81b73170a27

Exception on right click: 

https://gist.github.com/MairwunNx/6260ea7eb107d60f4cca5d1d5133f602

It exceptions fixed, and we can without problem use buttons and toggle buttons in projects 👍 
It PR also add ability to configure settings for button or togglebutton or menubutton animations or just behavior.

Ability to configure now:
> `rightClickIsEnabled` - default `false`, in windows also right click disabled, but if exists menu it automatically set to `true`. If needed force enable, just set to `true`.
> `shrinkAnimationIsEnabled` - default `true`, just controlling animation enabled state for instance, e.g scene or some parent, e.g `button`, or `toggle button`.
> `shrinkAnimationOnKeyPress` - i think it fully understand, what it do.
> `shrinkAnimationScaleFactor` - scale factor for shrink animation, default `0.97`, e.g we can set `0.5` for button and `0.99` for menu button.
> `defaultScaleXFactor` and `defaultScaleYFactor` - default scale factor what applied after shrink animation, it needed for extra cases, e.g if i use default scale as `2.0` inscead `1.0`. Default value is `1.0`.
> `shrinkAnimationDuration` - just animation duration. e.g we can set for `button` `400ms`, for `togglebutton` `60000000ms` :D. Default value 400ms.

### CODE REVIEW

**Comment by MairwunNx** [comment]
I also want to clarify that this PR does not fix problems for all other skins, I want to say they really are there. And it must be rewritten)) I can do it, but the release may be postponed for next day))

**Comment by MairwunNx** [comment]
`Simplified code for applyThemes(maybe duplicate).` commit causes problems with changing theme, please not merge PR, i revert it commit after college. 👍

**Comment by dukke** [comment]
Split this PR.

Make a PR just for the bug fixes alone. Another PR for the suggested changes like animation timing or whatever that are not critical.
Also would be nice to know when (and why) the bugs happen.

Thanks :) 👍

**Comment by MairwunNx** [comment]
Sorry, to separate them will not work, I want that it would be the same pr, it will have its merge as it is.

**Comment by dukke** [comment]
I still need to know what the bug is about. 

Usually each feature/bug fix is separated into its own PR. It's standard practice. Makes discussing the problem easier. 
Also when I merge, only one commit is stored in git history, so making several things only in one PR will mess up the git history.

**Pull request closed without merging**
