### PR TITLE
Hide cross for uneditable TextFields (disabled != uneditable)

### LINKED ISSUE #204: Add Maven/Gradle coordinates to README
These are already available from https://pixelduke.com/java-javafx-theme-jmetro/ but adding these to README directly will simplify using jmetro as an external library.

### LINKED ISSUE #209: TextFields - Non-Editable TextFields shouldn't have a 'clear' button
jmetro version: 11.6.15

The JMetro theme introduces an 'X' in TextField controls that provides a quick way to remove all text from a TextField. This functionality does not respect the editable property of a TextField. 

Even when a TextField is made non editable:

1) The 'X' symbol appears.
2) Clicking on the 'X' removes the text in the field rendering the application unusable. (User can no longer make forward progress because the text is gone but the field is not editable so nothing can be added back.)

Solution:

Ideally when a TextField is made non-editable the 'X' functionality should be disabled.

### PR DESCRIPTION
**Pull request by satsen**
Fixes #209
Fixes #204

Actually there was an issue (#180) and pull request made for this 1.5 years ago (#182) but because the author didn't explain which case wasn't covered previously, they got closed.

When you have a TextField with `setEditable(false)` (which keeps the same text style but makes it uneditable and is not the same as `setDisable(true)` which also makes it gray and unselectable), the cross is still there. This PR fixes that.

### CODE REVIEW

**Comment by satsen** [comment]
By the way, I also deleted the empty `jfxtras--styles` (with two dashes) folder.

**Comment by satsen** [comment]
@dukke

**Comment by satsen** [comment]
@dukke

**Comment by dukke** [comment]
Hi @satsen 

Truly sorry for the late reply. I've been very busy with my work.

Can we separate each PR into its own issue? That is, each PR solving just one issue.

Thanks and sorry again..

**Comment by dukke** [comment]
> By the way, I also deleted the empty `jmetro--samples` (with two dashes) folder. I also added Gradle & Maven dependency snippets. Just trying to fix up the repository a little 👍 Hope you can do a release after you merge the current open pull requests as well :)

The "jmetro-samples" folder exists for the master branch the other folder (jmetro--samples) is for the jdk-8 branch

**Comment by dukke** [comment]
.. having a PR for each separate issue is important because then we can discuss each issue individually and it's not an all or nothing approach.
For instance, the uneditable textfield issue could be merged immediately but because there are other things being changed in this PR that need to be discussed, it can't be merged.

**Comment by dukke** [comment]
All these has already been fixed.

I've put a reference to you on one of the commits. Thanks for your contribution.

**Comment by satsen** [comment]
@dukke Well it's unfortunate that this PR didn't get merged, I guess you could have removed the offending commits but yeah it is my fault for adding unrelated changes so I am sorry. At least I'm glad that the code helped, even if the PR did not.

Sorry for late reply as well.

**Comment by dukke** [comment]
No it's not your fault @satsen .
I (and the users of JMetro) just have to thank you for your contribution. 

Unfortunately I wasn't having time to work on JMetro, if I had I would have commented earlier and you would have made the change. Anyways, I put a reference to your username in the commit and there's always the chance that you'll file another PR that will get merged 🙂

**Pull request closed without merging**
