### PR TITLE
hyper-link metro dark and light styles additions.

### PR DESCRIPTION
**Pull request by MairwunNx**
It very simple hyper-link changes, basically changed hover \ pressed \ base color. 

###### base
image
###### hover
image
###### pressed
image
---
###### base
image
###### hover
image
###### pressed
image
###### base
image
###### hover
image
###### pressed
image

as base state text fill color used `accent_color`

review changes and commit it! 🙂

### CODE REVIEW

**Comment by dukke** [comment]
Great!

Comments:
- Use accent_color as color of hyperlink
Good call 👍 
- I think its better to have the hyperlink be underlined all the time even when the mouse isn't hover
- Please add sample in samples project.

Thanks for another addition to JMetro.

**Comment by MairwunNx** [comment]
1. Already used
2. Underline behavior getted by visited property, not by style
3. I try it

No problem 🙃

**Comment by dukke** [comment]
Thanks Pavel, good work! 👍 👍

**Comment by MairwunNx** [comment]
Thanks !😃

**Comment by dukke** [comment]
Merged this and will finish what's missing and what we have discussed. Thanks Pavel 👍

**Pull request merged**
