### PR TITLE
menu-button metro dark and light styles.

### PR DESCRIPTION
**Pull request by MairwunNx**
image

image

Other screenshots in #43 issue.

@dukke please, check and review changes, and if you like it merge my branch. 👍

### CODE REVIEW

**Comment by dukke** [comment]
Nice work.

Only a sample in the "samples" sub-project is missing.

**Comment by MairwunNx** [comment]
Thanks, samples in work or in processing :) It be added in other issue > PR

**Comment by dukke** [comment]
Add it in this PR. 
It is part of this issue. 
Thanks 👍

**Comment by dukke** [comment]
I will create the missing sample and make any more necessary adjustments if any are necessary. Thanks Pavel (@MairwunNx)! 👍

**Pull request merged**
